disabled_rules: # 禁用规则
- file_length
- line_length

opt_in_rules: # 启用制定的规则
- empty_count

  # 可以通过执行如下指令来查找所有可用的规则:
  # swiftlint rules
included: # 执行 linting 时包含的路径。如果出现这个 `--path` 会被忽略。
  - ./MicroBlog
excluded: # 执行 linting 时忽略的路径。 优先级比 `included` 更高。你所希望不要检索的路径,SwiftLint会无视掉该路径下的文件
  - Carthage
  - Pods

# 临时添加 处理
empty_count: warning
shorthand_operator: warning
function_body_length: 
    warning: 120

function_parameter_count:
    warning: 6
 
# 可配置的规则可以通过这个配置文件来自定义
# 二进制规则可以设置他们的严格程度
force_cast: warning # 隐式
force_try:
  severity: warning # 显式
# 同时有警告和错误等级的规则，可以只设置它的警告等级
# 隐式
line_length: 128
# 可以通过一个数组同时进行隐式设置
type_body_length:
  - 400 # warning
  - 800 # error
# 或者也可以同时进行显式设置
file_length:
  warning: 800
  error: 1200
# 命名规则可以设置最小长度和最大程度的警告/错误
# 此外它们也可以设置排除在外的名字
type_name:
  min_length: 4 # 只是警告
  max_length: # 警告和错误
    warning: 40
    error: 50
  excluded: iPhone # 排除某个名字
identifier_name:
  min_length: # 只有最小长度
    warning: 1
    #    error: 2 # 只有错误
  allowed_symbols: 
    - _ # 允许下划线
  validates_start_with_lowercase: false 
  excluded: # 排除某些名字
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode" # 报告类型 (xcode, json, csv, checkstyle, junit, html, emoji)
